name: Build slides

on:
  
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

#inspired by https://gist.github.com/farr/26d109d947a7ee4a35e37f7d77d91615
#and         https://github.com/xu-cheng/latex-action

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: slides.tex
          #totally unclear if I need this option for lualatex
          latexmk_use_xelatex: true

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF with slides
          path: slides.pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          #prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./slides.pdf
          asset_name: ${{ github.ref }}-slides.pdf
          asset_content_type: application/pdf
